#!/bin/sh

chown 0:0 -R /

# mount filesystem
mount -t tmpfs tmpfs /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mkdir -p /dev/pts
mount -t devpts -o gid=4,mode=620 none /dev/pts

# setup network
hostname linux
ip addr add 127.0.0.1/8 dev lo
ip link set lo up

# wait tsc
sleep 1

/bin/sh

poweroff -f
